### ISSUE TITLE
Database Creation: 'value' property under ThroughputMeasurement is doubled 

### ISSUE THREAD

**Issue by Linoyperetz** [RedisLabs/rl-cloud-api-sdk#69]
**Actual behavior**
On Database type, we have the following property: 
`    throughputMeasurement?: {
        by: DatabaseThroughputMeasurement;
        value: number;
    };`
And DatabaseThroughputMeasurement is:
`export declare type DatabaseThroughputMeasurement = {
    by: 'number-of-shards' | 'operations-per-second';
    value: number;
    [key: string]: any;
};`
Which means we should add the value twice.

**Expected behavior**
The value type will appear one time under ThroughputMeasurement.

**Comment by danitseitlin** [comment]
@Linoyperetz V1.1.1
