### ISSUE TITLE
Can't run updateDatabase on ROF cluster

### ISSUE THREAD

**Issue by Linoyperetz** [RedisLabs/rl-cloud-api-sdk#79]
Can't run updateDatabase on ROF cluster. 

Steps:
1. created a gcp rof subscription with 50gb and 5k ops/sec, replication enabled2
2. Use the updateDatabase call with the following update params:
`    dbGcpPreUpgradeUpdatedParameters = {
        memoryLimitInGb: 70,
        throughputMeasurement: {
            by: 'operations-per-second',
            value: 4000
        },
        supportOSSClusterApi: true,
        useExternalEndpointForOSSClusterApi: true,
        replication: false
    }`
3. get the following: 
` Request failed: 400, error_code: invalid_plan_request - average_value_size is required in ROF plans
RCP_GKE_rcp-testing2_qa2 qa2.web-6ccc95bfd5-xhx4h [22/Mar/2021:17:19:46 +`
The average_value_size property isn't supported.

Version 1.1.6

**Comment by danitseitlin** [comment]
@Linoyperetz Hi thanks for reaching.
I don't understand the peoblem, is it because the API is not passing the average value size by default? I can only add the key to the typw if it doesn't exist, but not sure I have more to supply here

**Comment by danitseitlin** [comment]
Seems like its not an ability in the update database api
